@startuml
class Poligono {
    + Poligono(_paiRef:Objeto, _rotulo:char, pontosPoligono:List<Ponto4D>)
    + GetIdxPontoMenorDistancia(sruPonto:Ponto4D) : int
    + <<override>> ToString() : string
}
Objeto <|-- Poligono
@enduml
